import { Mood, GeneratedContent, Language } from '../types/mood';

const quotes = {
  en: {
    Happy: [
      "Happiness is not something ready made. It comes from your own actions.",
      "The most wasted of all days is one without laughter.",
      "Happiness is when what you think, what you say, and what you do are in harmony.",
      "The purpose of our lives is to be happy.",
      "Happiness is the art of never holding in your mind the memory of any unpleasant thing that has passed.",
      "For every minute you are angry you lose sixty seconds of happiness.",
      "Happiness is not in the mere possession of money; it lies in the joy of achievement.",
      "The secret of happiness is freedom, the secret of freedom is courage.",
      "Count your age by friends, not years. Count your life by smiles, not tears.",
      "The best way to cheer yourself is to try to cheer someone else up.",
      "Joy is the simplest form of gratitude.",
      "Smiles are contagious. Be a carrier.",
      "Happiness depends upon ourselves.",
      "The only thing that will make you happy is being happy with who you are.",
      "Happiness is a direction, not a place.",
      "Happiness is not a goal; it is a by-product.",
      "Happiness depends on the quality of your thoughts.",
      "Happiness is the best makeup.",
      "Happiness is the secret to all beauty. There is no beauty without happiness.",
      "Be happy for this moment. This moment is your life.",
      "Happiness radiates like the fragrance from a flower and draws all good things towards you.",
      "Happiness is not something you postpone for the future; it is something you design for the present.",
      "Happiness is the highest form of health.",
      "The true secret of happiness lies in taking a genuine interest in all the details of daily life.",
      "Happiness grows at our own firesides, and is not to be picked in stranger's gardens.",
      "Happiness is the only thing that multiplies when you share it.",
      "Happiness is a choice, not a result. Nothing will make you happy until you choose to be happy.",
      "Happiness is not in what you have, but who you are.",
      "Happiness is found when you stop comparing yourself to other people.",
      "There is only one happiness in this life, to love and be loved.",
      "The happiest people don't have the best of everything, they just make the best of everything."
    ],
    Calm: [
      "Peace comes from within. Do not seek it without.",
      "Calm mind brings inner strength and self-confidence.",
      "The quieter you become, the more you can hear.",
      "In the midst of movement and chaos, keep stillness inside of you.",
      "Calmness is the cradle of power.",
      "Don't let people pull you into their storm. Pull them into your peace.",
      "Within you, there is a stillness and a sanctuary to which you can retreat at any time.",
      "Breath is the power behind all things. Peace and calm are just a breath away.",
      "The nearer a man comes to a calm mind, the closer he is to strength.",
      "Still waters run deep.",
      "Serenity is not freedom from the storm, but peace amid the storm.",
      "Calmness is the ability to think straight in the midst of chaos.",
      "Find peace in the silence of your mind.",
      "Let go of what you can't control and find your inner calm.",
      "Embrace the calm and let it rejuvenate your soul.",
      "Calmness is the foundation of emotional resilience.",
      "When you find peace within yourself, you become the kind of person who can live at peace with others.",
      "Calm seas never made a skilled sailor.",
      "Peace is not absence of conflict, it is the ability to handle conflict by peaceful means.",
      "To understand everything is to forgive everything.",
      "Calmness is the cradle of power.",
      "Nothing can bring you peace but yourself.",
      "Calm mind brings inner strength and self-confidence.",
      "Be calm, be kind. The universe has your back.",
      "In the midst of chaos, keep calm and carry on.",
      "Calmness doesn't come from outside. It comes from within.",
      "You cannot control the behavior of others, but you can always choose how you respond to it.",
      "Calmness of mind is one of the beautiful jewels of wisdom.",
      "Peace begins with a smile.",
      "Sometimes it's not the load that breaks you down, it's the way you carry it.",
      "Calmness is the art of being in the midst of chaos."
    ],
    Energetic: [
      "Energy and persistence conquer all things.",
      "Life is like riding a bicycle. To keep your balance, you must keep moving.",
      "The only way to do great work is to love what you do.",
      "Success is not final, failure is not fatal: it is the courage to continue that counts.",
      "Your energy introduces you before you even speak.",
      "Push yourself, because no one else is going to do it for you.",
      "The future depends on what you do today.",
      "The harder you work for something, the greater you'll feel when you achieve it.",
      "Wake up with determination, go to bed with satisfaction.",
      "Your attitude determines your direction.",
      "Stay positive, work hard, make it happen.",
      "Don't watch the clock; do what it does. Keep going.",
      "Be fearless in the pursuit of what sets your soul on fire.",
      "Dream it. Wish it. Do it.",
      "Success doesn't come to you, you go to it.",
      "Don't count the days, make the days count.",
      "Act as if what you do makes a difference. It does.",
      "The only limit to our realization of tomorrow is our doubts of today.",
      "Start where you are. Use what you have. Do what you can.",
      "Your limitation—it's only your imagination.",
      "Sometimes later becomes never. Do it now.",
      "Great things never come from comfort zones.",
      "Dream it. Believe it. Build it.",
      "Don't stop when you're tired. Stop when you're done.",
      "Wake up with determination; go to bed with satisfaction.",
      "Do something today that your future self will thank you for.",
      "Little things make big days.",
      "It's going to be hard, but hard does not mean impossible.",
      "Don't wait for opportunity. Create it.",
      "Sometimes we're tested not to show our weaknesses, but to discover our strengths.",
      "The key to success is to focus on goals, not obstacles.",
      "Believe you can and you're halfway there."
    ],
    Stressed: [
      "Take a deep breath. It's just a bad day, not a bad life.",
      "You are stronger than you think.",
      "This too shall pass.",
      "Stress is caused by being 'here' but wanting to be 'there'.",
      "The greatest weapon against stress is our ability to choose one thought over another.",
      "It's not the load that breaks you down, it's the way you carry it.",
      "Difficult roads often lead to beautiful destinations.",
      "Don't let yesterday take up too much of today.",
      "Sometimes the best thing you can do is not think, not wonder, not imagine, not obsess. Just breathe and have faith that everything will work out for the best.",
      "When you feel overwhelmed, remember: one step at a time.",
      "In the middle of difficulty lies opportunity.",
      "Relax, reset, recharge.",
      "Breathe in peace, breathe out stress.",
      "Let go and let be.",
      "Find strength in the struggle.",
      "Calm mind brings inner strength.",
      "You don't have to control your thoughts. You just have to stop letting them control you.",
      "Stress is an excuse to press pause.",
      "Keep calm and carry on.",
      "Sometimes the most productive thing you can do is relax.",
      "You don't have to see the whole staircase, just take the first step.",
      "It's okay to not be okay.",
      "Turn your wounds into wisdom.",
      "Every day may not be good... but there's something good in every day.",
      "Don't stress the could haves. If it should have, it would have.",
      "Let your worries drift away, find your peace today.",
      "Silence is sometimes the best answer.",
      "Your mind will answer most questions if you learn to relax and wait for the answer.",
      "Breathe. Let go. And remind yourself that this very moment is the only one you know you have for sure.",
      "Handle with care: Yourself.",
      "Do not anticipate trouble, or worry about what may never happen.",
      "Slow down and everything you are chasing will come around and catch you."
    ],
    Nostalgic: [
      "Memories warm you up from the inside.",
      "Sometimes you will never know the value of a moment until it becomes a memory.",
      "Life is not measured by the breaths we take, but by the moments that take our breath away.",
      "The best thing about memories is making them.",
      "Yesterday is but today's memory, tomorrow is today's dream.",
      "Some memories are unforgettable, remaining ever vivid and heartwarming.",
      "A moment lasts all of a second, but the memory lives on forever.",
      "The past beats inside me like a second heart.",
      "Memory is the diary that we all carry about with us.",
      "Good times become good memories and bad times become good lessons.",
      "Cherish the moments that become memories.",
      "Nostalgia is a file that removes the rough edges from the good old days.",
      "Every memory is a way to relive a piece of your past.",
      "Hold onto your memories; they are treasures of the heart.",
      "The magic of nostalgia is savoring the moments that shaped us.",
      "Memories are timeless treasures of the heart.",
      "Sometimes you will never know the value of a moment until it becomes a memory.",
      "The more you leave out, the more you highlight what you leave in.",
      "We do not remember days, we remember moments.",
      "Nostalgia is the happiest mistake of the heart.",
      "Memories are the key not to the past, but to the future.",
      "Look back with appreciation, forward with confidence.",
      "Those we love and lose are always connected by heartstrings into infinity.",
      "Remembering is easy; forgetting is hard.",
      "The only real treasure is in your head. Memories are better than diamonds and nobody can steal them from you.",
      "Memories are like a garden carried in the heart.",
      "There is nothing better than a friend, unless it is a friend with chocolate.",
      "The best memories are those we make with our friends.",
      "Memories are the architecture of the heart.",
      "Time may pass, but memories are timeless.",
      "Every memory is a photograph from the past with the eyes of the present."
    ],
    Creative: [
      "Creativity is intelligence having fun.",
      "Every artist was first an amateur.",
      "The creative adult is the child who survived.",
      "To practice any art, no matter how well or badly, is a way to make your soul grow.",
      "Creativity takes courage.",
      "Art enables us to find ourselves and lose ourselves at the same time.",
      "The worst enemy to creativity is self-doubt.",
      "You can't use up creativity. The more you use, the more you have.",
      "Creativity is contagious, pass it on.",
      "Everything you can imagine is real.",
      "Imagination is the beginning of creation.",
      "Creativity involves breaking out of established patterns.",
      "Think outside the box and let your ideas flow.",
      "Innovation distinguishes between a leader and a follower.",
      "Let your creativity shine and inspire others.",
      "Creativity is allowing yourself to make mistakes. Art is knowing which ones to keep.",
      "The chief enemy of creativity is 'good' sense.",
      "Creativity is seeing what everyone else has seen and thinking what no one else has thought.",
      "Don't think outside the box. Think like there is no box.",
      "Creativity is the power to connect the seemingly unconnected.",
      "Creativity is inventing, experimenting, growing, taking risks, breaking rules, making mistakes and having fun.",
      "You can't wait for inspiration. You have to go after it with a club.",
      "Creativity is a natural extension of our enthusiasm.",
      "Creativity is the way I share my soul with the world.",
      "The desire to create is one of the deepest yearnings of the human soul.",
      "Creativity takes courage and a willingness to fail.",
      "The creative process is a process of surrender, not control.",
      "Creativity is piercing the mundane to find the marvelous.",
      "Art is the only way to run away without leaving home.",
      "Creativity is thinking up new things. Innovation is doing new things.",
      "To live a creative life, we must lose our fear of being wrong."
    ]
  },
  zh: {
    Happy: [
      "幸福不是现成的，它来自于你自己的行动。",
      "最浪费的日子是没有笑声的日子。",
      "当你的思想、言语和行为和谐一致时，就是幸福。",
      "我们生命的目的就是要快乐。",
      "幸福就是永远不在心中保留任何不愉快的记忆。",
      "生气一分钟，就失去六十秒的幸福。",
      "幸福不在于拥有金钱，而在于获得成就的喜悦。",
      "幸福的秘诀是自由，自由的秘诀是勇气。",
      "用朋友而不是年龄来计算岁月，用微笑而不是眼泪来衡量人生。",
      "让自己开心的最好方法就是努力去让别人开心。",
      "喜悦是最简单的感恩形式。",
      "笑容是有传染性的。成为传染源。",
      "幸福取决于我们自己。",
      "让自己快乐的唯一方法是对自己满意。",
      "幸福是一种方向，而不是一个地点。",
      "幸福不是一个目标，而是一个副产品。",
      "幸福取决于你思想的质量。",
      "幸福是最好的化妆品。",
      "幸福是没有幸福的，只有健康的。",
      "为此刻感到快乐。此刻就是你的生活。",
      "幸福像花的香气一样散发，吸引所有美好的事物靠近你。",
      "幸福不是你为未来所做的准备，而是你为现在所做的设计。",
      "幸福是健康的最高形式。",
      "真正的幸福秘诀在于对日常生活中所有细节保持真正的兴趣。",
      "幸福在我们自己的炉边生长，而不是在陌生人的花园中采摘。",
      "幸福是唯一在你分享时会增多的东西。",
      "幸福是一个选择，而不是结果。直到你选择快乐，什么也不会让你快乐。",
      "幸福不在于你拥有多少，而在于你是谁。",
      "当你停止与他人比较时，你会发现自己的幸福。",
      "人生中唯一的幸福是爱与被爱。",
      "最快乐的人并不拥有最好的全部，他们只是善于处理一切。"
    ],
    Calm: [
      "内心的平静来自于内在，不要向外寻求。",
      "平静的心灵带来内在的力量和自信。",
      "你越安静，听到的就越多。",
      "在动荡和混乱中，保持内心的平静。",
      "平静是力量的摇篮。",
      "不要让别人把你拉进他们的风暴，要把他们拉进你的平静。",
      "在你内心有一片宁静和避难所，你随时都可以退居其中。",
      "呼吸是一切力量的源泉。平和与安宁只在呼吸之间。",
      "人越接近平静的心境，就越接近力量。",
      "静水流深。",
      "宁静不是免于风暴，而是在风暴中保持和平。",
      "平静是混乱中直思的能力。",
      "在心灵的寂静中找到和平。",
      "放下你无法控制的，找到内在的平静。",
      "拥抱宁静，让它滋养你的灵魂。",
      "平静的心灵是情绪恢复力的基础。",
      "当你在自己内心找到和平时，你会成为能够与他人和平相处的人。",
      "宁静的海洋从未造就过熟练的水手。",
      "和平不是冲突的缺席，而是通过和平手段处理冲突的能力。",
      "理解一切就是宽恕一切。",
      "平静是力量的基础。",
      "没有什么能带给你和平，除了你自己。",
      "平静的心灵带来内在的力量和自信。",
      "保持冷静并友善。宇宙支持你。",
      "在混乱中保持冷静，继续前进。",
      "平静不是来自外部，它来自内部。",
      "你无法控制他人的行为，但你总能选择如何回应。",
      "平静的心灵是智慧的美丽珍宝之一。",
      "和平始于微笑。",
      "有时候，最有成效的事情就是放松。",
      "你不必看到整个楼梯，只需迈出第一步。",
      "慢下来，一切你追逐的事物都会来到你身边。"
    ],
    Energetic: [
      "能量和毅力可以征服一切。",
      "生活就像骑自行车，要保持平衡就必须不断前进。",
      "做伟大的工作的唯一方法就是热爱你所做的事。",
      "成功不是终点，失败也不是致命的：重要的是继续前进的勇气。",
      "你的能量在你开口之前就已经介绍了你。",
      "推动自己，因为没有其他人会帮你做这件事。",
      "未来取决于你今天做什么。",
      "为某事越努力，达成时就会感觉越美好。",
      "带着决心醒来，带着满足入睡。",
      "你的态度决定你的方向。",
      "保持积极，努力工作，让它发生。",
      "不要看钟表；做它所做的。继续前进。",
      "在追求让你灵魂燃烧的事物时要无所畏惧。",
      "梦想它。希望它。做到它。",
      "成功不会主动找上门，你需要主动去追求。",
      "不要计算日子，要让日子有意义。",
      "像你做的事情那样行动，仿佛它们有所不同。它们确实是。",
      "真正的限制是我们的怀疑。",
      "从现在开始。用你所拥有的，做你所能做的。",
      "你的限制只有你的想象力。",
      "有时候，稍后会变成永不。现在就去做。",
      "伟大的事情永远不会来自舒适区。",
      "梦想。相信。建设。",
      "当你累了，不要停止。当完成时，停止。",
      "带着决心醒来；带着满足入睡。",
      "做一些今天你的未来自我会感谢你的事情。",
      "小事情成就大日子。",
      "这会很难，但难不意味着不可能。",
      "不要等待机会，创造机会。",
      "有时候，我们的测试不是为了展示我们的弱点，而是为了发现我们的力量。",
      "成功的关键是专注于目标，而不是障碍。",
      "相信你能，你已经完成了一半。"
    ],
    Stressed: [
      "深呼吸，这只是糟糕的一天，而不是糟糕的人生。",
      "你比你想象的更强大。",
      "这也将过去。",
      "压力来自于身在此处，却想在彼处。",
      "对抗压力最大的武器是我们选择一个想法而不是另一个的能力。",
      "压垮你的不是负担本身，而是你承担的方式。",
      "艰难的道路往往通向美丽的目的地。",
      "不要让昨天占据了太多的今天。",
      "有时候最好的办法就是不思考，不怀疑，不想象，不执着。只要呼吸，相信一切都会变好。",
      "当你感到不知所措时，请记住：一步一步来。",
      "困难中蕴藏着机遇。",
      "放松，重置，充电。",
      "吸气带来和平，呼气带走压力。",
      "放手并顺其自然。",
      "在挣扎中找到力量。",
      "平静的心灵带来内在的力量。",
      "你不必控制你的思想，只需停止让它们控制你。",
      "压力是按下暂停键的借口。",
      "保持冷静并继续前进。",
      "有时候，最有成效的事情就是放松。",
      "你不必看到整个楼梯，只需迈出第一步。",
      "压力是一种进步的信号，不是失败的标志。",
      "控制不了的事情，我们就不要去担心。",
      "放松一下，给自己一个暂停的机会。",
      "用冷静面对压力，用智慧解决问题。",
      "不要急于解决一切，给自己时间。",
      "学会接受你无法改变的事情。",
      "让你的呼吸引导你走向平静。",
      "每一次呼吸都是一次新开始。",
      "放下不必要的负担，轻装前行。",
      "在压力中寻找平衡，在挑战中成长。",
      "给自己一点时间，平复心情。",
      "用积极的心态面对压力，转化为动力。"
    ],
    Nostalgic: [
      "回忆让你从内心感到温暖。",
      "有时候你永远不会知道一个时刻的价值，直到它成为回忆。",
      "生命不是用我们呼吸的次数来衡量，而是那些让我们屏住呼吸的时刻。",
      "关于回忆最好的事情就是创造回忆。",
      "昨天不过是今天的记忆，明天是今天的梦想。",
      "有些回忆难以忘怀，永远鲜活而温暖。",
      "一个瞬间只持续一秒钟，但记忆永远长存。",
      "过去在我内心跳动，如同第二颗心脏。",
      "记忆是我们随身携带的日记。",
      "美好的时光成为美好的回忆，糟糕的时光成为宝贵的教训。",
      "珍惜成为回忆的时刻。",
      "怀旧的魔力在于品味塑造我们的那些时刻。",
      "每一个记忆都是重温过去的一部分。",
      "抓住你的记忆，它们是心灵的珍宝。",
      "怀旧的魔力在于回味那些塑造我们的时刻。",
      "回忆是心灵的镜子，反映出过去的美好。",
      "每一次回忆都是一次心灵的旅行。",
      "记忆是一座桥梁，连接着过去与未来。",
      "珍惜每一个瞬间，因为它们会成为美好的回忆。",
      "回忆让我们不忘初心，继续前行。",
      "温暖的回忆如同春日的阳光，照亮我们的心房。",
      "回忆是时间赠予我们的珍贵礼物。",
      "往日的时光如同星辰，闪耀在记忆的天空。",
      "回忆是灵魂的花园，需要精心呵护。",
      "时光荏苒，唯有回忆永恒。",
      "记忆是我们心中的宝库，珍藏着无尽的故事。",
      "每一个微笑的瞬间，都是美好回忆的一部分。",
      "回忆是生命的诗篇，吟唱着过去的旋律。",
      "怀念那些美好的日子，让心灵得到滋养。",
      "回忆是时间织就的画卷，色彩斑斓。",
      "在回忆中，我们找到了属于自己的宁静。",
      "每一次回首，都是对过去的致敬。"
    ],
    Creative: [
      "创造力是智慧在玩耍。",
      "每个艺术家最初都是业余的。",
      "有创造力的成年人是幸存下来的孩子。",
      "练习任何艺术，无论好坏，都是让灵魂成长的方式。",
      "创造力需要勇气。",
      "艺术使我们既能找到自己，又能迷失自己。",
      "创造力最大的敌人是自我怀疑。",
      "创造力用不完。越用越多。",
      "创造力是会传染的，把它传递下去。",
      "你能想象的一切都是真实的。",
      "想象力是创造的开始。",
      "创造力涉及突破既定模式。",
      "跳出框框，让你的想法流淌。",
      "创新区分领导者和跟随者。",
      "让你的创造力闪耀并激励他人。",
      "创造力是允许自己犯错的过程。艺术是知道哪些错需要保留。",
      "创造力是‘好’感官的最大敌人。",
      "创造力是看见别人看见的，却思考别人未曾思考的。",
      "不要在框框外思考。想象没有框框。",
      "创造力是连接看似无关事物的力量。",
      "创造力是发明、实验、成长、冒险、打破规则、犯错和享受乐趣。",
      "你不能等待灵感。你必须用棍棒去追击它。",
      "创造力是我们热情的自然延伸。",
      "创造力是我与世界分享灵魂的方式。",
      "创造力是人类灵魂最深的渴望之一。",
      "创造力需要勇气和愿意失败。",
      "创造过程是一个放手的过程，而不是控制。",
      "创造力是穿透平凡，发现奇妙。",
      "艺术是唯一可以在不离开家的情况下逃离的方式。",
      "创造力是想出新东西，创新是做新东西。",
      "为了过一个有创意的生活，我们必须摆脱对错误的恐惧。"
    ]
  }
};

export const generateContent = (mood: Mood, language: Language): GeneratedContent => {
  const moodQuotes = quotes[language][mood.name as keyof typeof quotes.en] || quotes[language].Happy;
  const randomQuote = moodQuotes[Math.floor(Math.random() * moodQuotes.length)];

  return {
    id: Date.now().toString(),
    mood,
    quote: randomQuote,
    timestamp: new Date(),
    language
  };
};